services:
  db_mysql_chocotejas:
    container_name: db_mysql_container_chocotejas
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:3306"   # host:contenedor
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_SERVICE_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: no
    volumes:
      - mysql_data_chocotejas:/var/lib/mysql

  sistema-chocotejas:
    container_name: sistema-chocotejas_container
    build:
      context: .
      dockerfile: Dockerfile
    image: sistema-chocotejas-image
    ports:
      - "${SISTEMA_CHOCOTEJAS_PORT}:${SISTEMA_CHOCOTEJAS_PORT}"
    environment:
      SERVER_PORT: ${SISTEMA_CHOCOTEJAS_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
    depends_on:
      - db_mysql_chocotejas
    volumes:
      - ./imagenes:/app/imagenes
      - ./logos:/app/logos
      - ./sliders:/app/sliders
      - ./momentos:/app/momentos

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin:latest
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db_mysql_chocotejas   # fija el servidor MySQL
      PMA_ARBITRARY: 0
    depends_on:
      - db_mysql_chocotejas
      - sistema-chocotejas

  # Servicio Node 1 - Estadísticas de Ventas
  node-service-1:
    container_name: node-service-1
    build:
      context: ./node-services/service-1
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      SERVICE_NAME: "Estadísticas de Ventas"
    volumes:
      - ./node-services/service-1:/app
      - /app/node_modules

  # Servicio Node 2 - Análisis de Productos
  node-service-2:
    container_name: node-service-2
    build:
      context: ./node-services/service-2
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      SERVICE_NAME: "Análisis de Productos"
    volumes:
      - ./node-services/service-2:/app
      - /app/node_modules

  # Servicio Node 3 - Reportes de Clientes
  node-service-3:
    container_name: node-service-3
    build:
      context: ./node-services/service-3
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      SERVICE_NAME: "Reportes de Clientes"
    volumes:
      - ./node-services/service-3:/app
      - /app/node_modules

volumes:
  mysql_data_chocotejas:
