server:
  port: ${SISTEMA_CHOCOTEJAS_PORT}

spring:
  application:
    name: sistema-chocotejas

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db_mysql_chocotejas:3306/BDChocotejas?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:SHccVE07.}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
    open-in-view: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

file:
  upload-dir: ${UPLOAD_DIR:./imagenes/}
  logo-dir: ${LOGO_DIR:./logos/}
  slider-dir: ${SLIDER_DIR:./sliders/}
  momentos-dir: ${MOMENTOS_DIR:./momentos/}

# Configuraci√≥n de servicios Node externos
node:
  service1:
    url: ${NODE_SERVICE1_URL:http://node-service-1:3001}
  service2:
    url: ${NODE_SERVICE2_URL:http://node-service-2:3002}
  service3:
    url: ${NODE_SERVICE3_URL:http://node-service-3:3003}
